### ISSUE TITLE
org.parceler.v: Unable to create ParcelableFactory for com.github.snowdream.android.app.books.b.a

### ISSUE THREAD

**Issue by snowdream** [snowdream/snowdream-books-android#2]
``` java
E/AndroidRuntime(19786): Process: com.github.snowdream.android.apps.books, PID: 19786
E/AndroidRuntime(19786): org.parceler.v: Unable to create ParcelableFactory for com.github.snowdream.android.app.books.b.a
E/AndroidRuntime(19786):        at org.parceler.x.a(Unknown Source)
E/AndroidRuntime(19786):        at org.parceler.Parcels.a(Unknown Source)
E/AndroidRuntime(19786):        at org.parceler.NonParcelRepository$ListParcelable.writeToParcel(Unknown Source)
E/AndroidRuntime(19786):        at android.os.Parcel.writeParcelable(Parcel.java:1357)
E/AndroidRuntime(19786):        at android.os.Parcel.writeValue(Parcel.java:1262)
E/AndroidRuntime(19786):        at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
E/AndroidRuntime(19786):        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
E/AndroidRuntime(19786):        at android.os.Bundle.writeToParcel(Bundle.java:1096)
E/AndroidRuntime(19786):        at android.os.Parcel.writeBundle(Parcel.java:663)
E/AndroidRuntime(19786):        at android.support.v4.app.FragmentState.writeToParcel(Unknown Source)
E/AndroidRuntime(19786):        at android.os.Parcel.writeTypedArray(Parcel.java:1191)
E/AndroidRuntime(19786):        at android.support.v4.app.FragmentManagerState.writeToParcel(Unknown Source)
E/AndroidRuntime(19786):        at android.os.Parcel.writeParcelable(Parcel.java:1357)
E/AndroidRuntime(19786):        at android.os.Parcel.writeValue(Parcel.java:1262)
E/AndroidRuntime(19786):        at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
E/AndroidRuntime(19786):        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
E/AndroidRuntime(19786):        at android.os.Bundle.writeToParcel(Bundle.java:1096)
E/AndroidRuntime(19786):        at android.os.Parcel.writeBundle(Parcel.java:663)
E/AndroidRuntime(19786):        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2884)
E/AndroidRuntime(19786):        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3261)
E/AndroidRuntime(19786):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(19786):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(19786):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(19786):        at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime(19786):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19786):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(19786):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime(19786):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
W/ActivityManager(  746):   Force finishing activity com.github.snowdream.android.apps.books/com.github.snowdream.android.app.books.MainActivity
```

**Comment by snowdream** [comment]
Fix: closed #2
close proguard

**Comment by billmote** [comment]
What rule(s) did you add to resolve this?  Currently experiencing the same thing.  I have the following 4 rules:

# Parceler configuration

-keep interface org.parceler.Parcel
-keep @org.parceler.Parcel class \* { _; }
-keep class *_$$Parcelable { *; }
-keep class org.parceler.Parceler$$Parcels

**Comment by snowdream** [comment]
@androidfu Thank you.
